language: generic

branches:
  except:
    - gh-pages

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -q
  - sudo apt-get install -y doxygen

after_success:
  - bash doc/deploy.sh
