language: generic

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

after_success:
  - bash doc/deploy.sh
